### ISSUE TITLE
`weathercan` article

### ISSUE THREAD

**Issue by steffilazerte** [vegmod/meteoland#1]
I have an article about using `weathercan` data in `meteoland` here: http://ropensci.github.io/weathercan/articles/articles/meteoland.html. 

I think it still needs some formatting (i.e. omit progress messages for the article), but I was wondering if you'd have the chance to check it out and make sure I'm not doing anything horrendously wrong!

It's a dummy example, so probably not an interpolation that should be used 'in real life', but I wanted to show case how the two packages could intersect.

Thanks!

**Comment by miquelcaceres** [comment]
Hi Steffi,

Thanks for writing this example! Besides the progress messages, I would improve the example by adding a few more stations south of those selected, and interpolating directly on a SpatialGridTopography. Perhaps you can have two sections, one for interpolation on specific points and another for creating an interpolated grid.

Best wishes,
Miquel

**Comment by steffilazerte** [comment]
Thanks for the feedback, I'll look into it and let you know what I come up with!
