### ISSUE TITLE
How to access the "unformatted_meteo" and "raster_meteo_reference" data?

### ISSUE THREAD

**Issue by Freestyleyang** [vegmod/meteoland#18]
Hi There,

Thank you for developing this great R package! I am following the tutorial at [https://cran.r-project.org/web/packages/meteoland/vignettes/reshaping-meteo.html](url). However, I notice that the data "unformatted_meteo" and "raster_meteo_reference" are not included in the package. I wonder how to obtain the data? Thanks. 

Regards,
Yang

**Comment by MalditoBarbudo** [comment]
Hi @Freestyleyang,

`unformatted_meteo` and `raster_meteo_reference` are just examples created on the fly for the tutorial and are not provided in the package. You can reproduce `unformatted_meteo` with:

```
unformatted_meteo <- tibble(
  date = rep(seq(from = as.Date("2022-12-01"), to = as.Date("2022-12-05"), by = 1), 3),
  station = rep(letters[1:3], each = 5),
  latitude = rep(c(41.35, 40.11, 42.00), each = 5),
  longitude = rep(c(-0.33, 0.12, 1.12), each = 5),
  min_temp = rnorm(15, 10, 6),
  max_temp = min_temp + rnorm(15, 10, 3),
  rh = rnorm(15, 50, 25)
) |>
  dplyr::mutate(
    rh = dplyr::if_else(rh > 100, 100, rh),
    rh = dplyr::if_else(rh < 20, 20, rh)
  )
```

And `raster_meteo_reference`  is just a raster with meteo variables. You can create one with:

```
raster_meteo_reference <- interpolate_data(
  raster_to_interpolate_example, meteoland_interpolator_example, verbose = FALSE
)
```
