### ISSUE TITLE
dependency on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [vegmod/meteoland#19]
(from email a month ago) meteoland depends on (depends, imports or suggests) one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html).

Please also urgently see https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1. Your package may start failing CRAN checks as soon as June 2023, when **sp** changes from business-as-usual (evolution status 0) to evolution status 2, that is using **sf** in place of **rgdal**.

You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023.

This CMD check log came from `_SP_EVOLUTION_STATUS_=2 R CMD check meteoland_2.0.0.tar.gz` which will be the default setting from June 2023, that is `sp` using `sf` in place of `rgdal`:
[00check.log](https://github.com/emf-creaf/meteoland/files/11301307/00check.log)
which you will need to debug yourself. You need to do this by June 2023, when `sp` flips evolution status from 0 to 2.

**Comment by rsbivand** [comment]
The problem for the forthcoming change of `sp` from evolution status 0 to 2 next month was that correctionpoints() uses sp::spTransform(), but passes an `"SpatialPointsMeteorology"` object for which there is no `sp::geometry()` method needed for coercing to `sf` in order to use `sf::st_transform()`. The attached modified file (in zip archive): 
[correctionpoints.zip](https://github.com/emf-creaf/meteoland/files/11407706/correctionpoints.zip)
yields the following check log when run with `_SP_EVOLUTION_STATUS_=2`: 
[00check.log](https://github.com/emf-creaf/meteoland/files/11407711/00check.log).

When run with `_SP_EVOLUTION_STATUS_=2` and without retiring packages on the library path, the check log is: 
[00check.log](https://github.com/emf-creaf/meteoland/files/11407735/00check.log)
showing that the placing of `rgdal` is superfluous and should be dropped.

**Comment by MalditoBarbudo** [comment]
@rsbivand
We are preparing an updated version to be released late May without any dependency on `rgdal`, `sp`, or `raster`. This new versión will drop any class based on `sp` classes and in local checks is passing with any value of `_SP_EVOLUTION_STATUS_`.
This version is on the branch `dep_removal` and is getting its final touches to be ready to release, hopefully in two weeks.

**Comment by MalditoBarbudo** [comment]
@rsbivand 
New version (v2.0.1) is on CRAN. This fixes any issues with `sp`, `rgeos` or `rgdal` as they are not dependencies of the package in this version.
