### ISSUE TITLE
`initial_Rp` parameter calculated badly in lat long coordinates

### ISSUE THREAD

**Issue by MalditoBarbudo** [vegmod/meteoland#22]
`initial_Rp` parameter should be calculated in meters, but when meteo data has lat/long coordinates, is calculated in degrees

**Comment by miquelcaceres** [comment]
I am not sure initial_Rp should be in meters, if the meteo and target spatial objects are in lat/long (or other crs).

**Comment by MalditoBarbudo** [comment]
You are completly right. Reverted.
