### ISSUE TITLE
Adopt CF conventions for NetCDF

### ISSUE THREAD

**Issue by miquelcaceres** [vegmod/meteoland#3]
NetCDF files written/read by meteoland should follow standard conventions
http://cfconventions.org/index.html

**Comment by miquelcaceres** [comment]
Conventions should be followed for grid mappings (section http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#grid-mappings-and-projections)

**Comment by MalditoBarbudo** [comment]
Starting with meteoland 2.0.0 functions for interacting with NetCDF files are deprecated.
Closing this issue.
